import type { OpusDeliverable } from "@/lib/ai/opus-package";
import { riskFlagsRequireHumanApproval } from "@/lib/policy";
import { getContentPipelineDataSourceId, getNotionClient } from "./client";

export type NotionSaveMode = "draft" | "review";

function richText(content: string) {
  const value = content || "—";
  return value.match(/[\s\S]{1,1900}/g)?.map((chunk) => ({
    type: "text" as const,
    text: { content: chunk },
  })) ?? [{ type: "text" as const, text: { content: "—" } }];
}

function paragraph(content: string) {
  return {
    object: "block" as const,
    type: "paragraph" as const,
    paragraph: { rich_text: richText(content) },
  };
}

function heading(content: string) {
  return {
    object: "block" as const,
    type: "heading_2" as const,
    heading_2: { rich_text: richText(content) },
  };
}

export async function saveDeliverableToNotion(
  deliverable: OpusDeliverable,
  mode: NotionSaveMode,
) {
  const notion = getNotionClient();
  const approvalRequired = riskFlagsRequireHumanApproval(deliverable.riskFlags);
  const stage = mode === "review" ? "Approval" : "Inbox";
  const approval = mode === "review" || approvalRequired ? "Needs approval" : "N/A";
  const risks = deliverable.riskFlags.length
    ? deliverable.riskFlags.join(", ")
    : "None detected";

  const page = await notion.pages.create({
    parent: {
      type: "data_source_id",
      data_source_id: getContentPipelineDataSourceId(),
    },
    properties: {
      Deliverable: { title: richText(deliverable.deliverable) },
      Stage: { select: { name: stage } },
      Approval: { select: { name: approval } },
      "Boost Status": { select: { name: "Not planned" } },
      "Paid-use rights": { select: { name: "Unknown" } },
      Job: { select: { name: deliverable.job } },
      Funnel: { select: { name: deliverable.funnel } },
      "Source Lane": { select: { name: deliverable.sourceLane } },
      Format: { select: { name: deliverable.format } },
      Channel: {
        multi_select: deliverable.channels.map((name) => ({ name })),
      },
      Campaign: { rich_text: richText(deliverable.campaign) },
      Hook: { rich_text: richText(deliverable.hook) },
      "One Message": { rich_text: richText(deliverable.oneMessage) },
      Proof: { rich_text: richText(deliverable.proof) },
      CTA: { rich_text: richText(deliverable.cta) },
      "Primary KPI": { select: { name: deliverable.primaryKpi } },
      "Test Variable": { select: { name: deliverable.testVariable } },
      Notes: {
        rich_text: richText(
          `Generated by OPUS Creative Worker AI package lane. Risk flags: ${risks}. Human review remains authoritative.`,
        ),
      },
    },
    children: [
      paragraph("Generated by OPUS Creative Worker. This page does not grant approval, paid-use rights, clinical clearance, scheduling, or publishing authority."),
      heading("Editorial premise"),
      paragraph(deliverable.editorialPremise),
      heading("Why this matters"),
      paragraph(deliverable.whyThisMatters),
      heading("On-screen title"),
      paragraph(deliverable.copy.onScreenTitle),
      heading("Caption"),
      paragraph(deliverable.copy.caption),
      ...(deliverable.copy.storyFrames.length
        ? [
            heading("Story sequence"),
            paragraph(
              deliverable.copy.storyFrames
                .map((frame, index) => `${index + 1}. ${frame}`)
                .join("\n"),
            ),
          ]
        : []),
      heading("Quality gate"),
      paragraph(
        `${deliverable.qualityGate.score}/5 · ${[
          deliverable.qualityGate.utility && "Utility",
          deliverable.qualityGate.novelty && "Novelty",
          deliverable.qualityGate.desire && "Desire",
          deliverable.qualityGate.humanity && "Humanity",
          deliverable.qualityGate.proof && "Proof",
        ]
          .filter(Boolean)
          .join(" · ") || "No dimensions passed"}`,
      ),
      heading("Risk flags"),
      paragraph(risks),
      heading("Next step"),
      paragraph(deliverable.nextStep),
    ],
  });

  return {
    id: page.id,
    url: "url" in page ? page.url : null,
    stage,
    approval,
  };
}
