'use client';
import { useEffect,useMemo,useState } from 'react';
import { cloudV2Packages,type CloudPackage } from '@/lib/cloud-v2-packages';
type Decision='RECOMMENDED'|'APPROVED'|'PASS'; type Stage='TODAY'|'PRODUCTION'|'READY';
type PackOutput={role:string;title:string;templateId:string;qa:{status:string;reasons:string[]}};
type Item=CloudPackage&{decision:Decision;stage:Stage;recommended:boolean;compliance:'CLEAR'|'CHECK';outputs:string[];rationale:string;jobState?:string;canvaUrl?:string;error?:string;packState?:string;packOutputs?:PackOutput[];packError?:string};
const KEY='opus-creative-os-v04-thursday';
const priority=['opus-04e9e898fc71','opus-f28e0d28b915','opus-dcb641f936fc','opus-afb7e620170d'];
const outputMap:Record<string,string[]>={'opus-04e9e898fc71':['IG Reel','TikTok','YouTube Short'],'opus-f28e0d28b915':['IG Reel','TikTok','Story'],'opus-dcb641f936fc':['IG Reel','Story','TikTok'],'opus-afb7e620170d':['IG Carousel/Reel','Story'],'opus-31e345937a0f':['IG Reel','TikTok','Story'],'opus-ee247f427667':['IG Reel','TikTok','Story'],'opus-4976083473be':['IG Reel','TikTok'],'opus-dfa0d1bd747f':['Google Business','IG Reel']};
const rationale:Record<string,string>={'opus-04e9e898fc71':'Strong surgeon-authority answer with a useful consultation insight.','opus-f28e0d28b915':'Sharp consumer-education hook with immediate save value.','opus-dcb641f936fc':'Makes the patient experience concrete through Tamara instead of generic service language.','opus-afb7e620170d':'Clean introduction that gives Tamara a real role in the OPUS story.','opus-31e345937a0f':'Specific evidence standard that reinforces the before/after accountability position.','opus-ee247f427667':'Human, light construction content that breaks up the authority-heavy batch.','opus-4976083473be':'Contrarian surgeon-selection hook with strong search/social utility.','opus-dfa0d1bd747f':'Strong judgment signal, but safety language needs deliberate review.'};
const seed=()=>cloudV2Packages.map(x=>({...x,decision:'RECOMMENDED' as Decision,stage:'TODAY' as Stage,recommended:priority.includes(x.id),compliance:(x.reviewFlags.some(f=>/medical|before\/after|service|verify/i.test(f))?'CHECK':'CLEAR') as 'CLEAR'|'CHECK',outputs:outputMap[x.id]??['IG Reel'],rationale:rationale[x.id]??'Useful source-backed moment from the Thursday batch.'}));
function stamp(n:number){return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}
export function CreativeDesk(){
 const [tab,setTab]=useState<Stage>('TODAY'); const [expanded,setExpanded]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null); const [packBusy,setPackBusy]=useState<string|null>(null); const [hydrated,setHydrated]=useState(false); const [items,setItems]=useState<Item[]>(seed);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setItems(JSON.parse(raw))}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(KEY,JSON.stringify(items))},[items,hydrated]);
 const visible=useMemo(()=>items.filter(x=>x.stage===tab&&x.decision!=='PASS').sort((a,b)=>Number(b.recommended)-Number(a.recommended)),[items,tab]); const recommended=items.filter(x=>x.stage==='TODAY'&&x.recommended&&x.decision==='RECOMMENDED'); const approved=items.filter(x=>x.stage==='PRODUCTION').length;
 async function make(id:string){setBusy(id);setItems(xs=>xs.map(x=>x.id===id?{...x,decision:'APPROVED',stage:'PRODUCTION',jobState:'QUEUED'}:x));try{const r=await fetch('/api/production',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:id})});const job=await r.json();setItems(xs=>xs.map(x=>x.id===id?{...x,jobState:job.state,canvaUrl:job.canvaUrl,error:job.error||(job.needsConnection?'Canva Connect authorization required to create the design.':undefined)}:x))}catch{setItems(xs=>xs.map(x=>x.id===id?{...x,jobState:'BLOCKED',error:'Production job request failed'}:x))}finally{setBusy(null)}}
 async function packageIt(id:string){
  if(id!=='opus-f28e0d28b915')return;
  setPackBusy(id);
  try{
   const r=await fetch('/api/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:id,campaignOrWeek:'W3',job:'Trust',sourceLane:'Frew',slug:'before-after',primaryTemplateId:'OPUS-TPL-PORTRAIT-9X16-E-V01',channels:['Instagram','TikTok','YouTube','Facebook'],approval:'Needs approval',date:'20260915',fields:{series:'ASK DR. FREW',headline:'BEFORE / AFTER',hook:'What can make a comparison look impressive—but tell you less than you think?',support:'What can make a comparison look impressive—but tell you less than you think?',cta:'WATCH THE ANSWER',physician:'DR. TYLER FREW · PLASTIC SURGEON'}})});
   const data=await r.json();
   if(!r.ok)throw new Error(data.error||'Pack request failed');
   setItems(xs=>xs.map(x=>x.id===id?{...x,packState:data.pack?.state,packOutputs:data.pack?.outputs,packError:undefined}:x));
  }catch(error){setItems(xs=>xs.map(x=>x.id===id?{...x,packState:'PACK_BLOCKED',packError:error instanceof Error?error.message:'Pack request failed'}:x))}finally{setPackBusy(null)}
 }
 async function makeBatch(){for(const x of [...recommended])await make(x.id)}
 const pass=(id:string)=>setItems(xs=>xs.map(x=>x.id===id?{...x,decision:'PASS'}:x));
 return <main><section className="cockpitHead"><div><p className="eyebrow">OPUS CREATIVE OS / V0.5</p><h1>Make the week.</h1><p className="lede">MAKE IT creates the primary production job. PACKAGE IT turns a proven primary into a bounded multi-surface pack without inventing new strategy or auto-publishing.</p></div><div className="weekBox"><span className="tiny">THIS BATCH</span><strong>{recommended.length} recommended now</strong><p>One approval can move the recommended batch into production.</p><button onClick={makeBatch} disabled={!recommended.length||!!busy}>MAKE RECOMMENDED {recommended.length}</button></div></section>
 <nav className="cockpitNav">{(['TODAY','PRODUCTION','READY'] as Stage[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}{x==='PRODUCTION'&&approved?` · ${approved}`:''}</button>)}</nav>
 {tab==='TODAY'&&<section className="briefStrip"><div><span className="tiny">SYSTEM READ</span><b>{recommended.length?`${recommended.length} things worth making first.`:'Recommended batch moved.'}</b></div><p>Your decisions are persistent on this device. Canva jobs expose their real connection/creation state instead of pretending compilation happened.</p></section>}
 <section className="makeGrid">{visible.map((item,index)=><article className={`makeCard ${item.recommended?'recommended':''}`} key={item.id}><div className="poster"><span className="posterNo">{String(index+1).padStart(2,'0')}</span><span className="posterKicker">{item.topic.replaceAll('_',' ')}</span><strong>{item.cover}</strong><span className="posterSource">{stamp(item.start)}–{stamp(item.end)}</span></div><div className="makeBody"><div className="cardTop"><span className="tiny">{item.recommended?'MAKE FIRST':'OPTIONAL'}</span><div className="signals"><span className="creativeSignal">CREATIVE · READY</span><span className={item.compliance==='CLEAR'?'clearSignal':'checkSignal'}>COMPLIANCE · {item.compliance}</span></div></div><h2>{item.hook}</h2><p className="rationale">{item.rationale}</p><div className="outputs">{item.outputs.map(x=><span key={x}>{x}</span>)}</div><div className="proposed"><span className="tiny">PROPOSED CAPTION</span><p>{item.caption}</p><b>{item.cta}</b></div>
 {item.jobState&&<div className="sourceDetails"><span className="tiny">PRODUCTION JOB · {item.jobState}</span>{item.canvaUrl?<p><a href={item.canvaUrl} target="_blank" rel="noreferrer">OPEN CANVA DESIGN ↗</a></p>:item.error?<p>{item.error}</p>:<p>Compiler running.</p>}</div>}
 {item.packState&&<div className="sourceDetails"><span className="tiny">PRODUCTION PACK · {item.packState}</span>{item.packError?<p>{item.packError}</p>:item.packOutputs?.map(output=><p key={output.role}><b>{output.role}</b> · {output.templateId} · {output.qa.status}</p>)}</div>}
 {expanded===item.id&&<div className="sourceDetails"><span className="tiny">SOURCE DETAILS</span><p>“{item.transcript}”</p><p>{item.file} · {stamp(item.start)}–{stamp(item.end)} · worker {item.tier}-tier {Math.round(item.score*100)}</p></div>}
 <div className="decisionRow">{tab==='TODAY'&&<button onClick={()=>make(item.id)} disabled={busy===item.id}>{busy===item.id?'STARTING…':'MAKE IT'}</button>}{tab==='PRODUCTION'&&item.id==='opus-f28e0d28b915'&&<button onClick={()=>packageIt(item.id)} disabled={packBusy===item.id}>{packBusy===item.id?'PACKING…':'PACKAGE IT'}</button>}<button className="quiet" onClick={()=>setExpanded(expanded===item.id?null:item.id)}>{expanded===item.id?'CLOSE':'CHANGE / SOURCE'}</button>{tab==='TODAY'&&<button className="quiet" onClick={()=>pass(item.id)}>PASS</button>}</div></div></article>)}</section>
 {!visible.length&&<section className="emptyState"><p className="eyebrow">{tab}</p><h2>{tab==='TODAY'?'Decision inbox cleared.':'Nothing here yet.'}</h2></section>}<footer className="cockpitFoot"><span>PERSISTENT DECISIONS · PRODUCTION JOBS · PROVEN PACK PROFILES</span><span>NO AUTO-PUBLISH · APPROVAL + COMPLIANCE GATES PRESERVED</span></footer></main>
}
