export type CloudPackage = {
  id: string; lane: 'youtube_anchor'|'shorts'|'paid'|'stories'|'website'|'google_business'; topic: string;
  file: string; start: number; end: number; transcript: string; tier: 'S'|'A'|'B'; score: number;
  hook: string; cover: string; caption: string; cta: string; reviewFlags: string[];
};

export const cloudV2Summary = { runId:'opus-cloud-thursday-2026-09-10-v2', mediaFiles:23, candidates:148, sTier:28, aTier:100, totalPackages:29, needsReview:29, roughCuts:3 } as const;

// Editorial shortlist: worker ranking is an input, not the final taste decision.
// Transcript text below is trimmed only at obvious slate/question boundaries; meaning is preserved.
export const cloudV2Packages: CloudPackage[] = [
 {id:'opus-04e9e898fc71',lane:'youtube_anchor',topic:'surgeon_judgment',file:'MVI_8496.MOV',start:76.91,end:99.83,transcript:"I think something that we don't always talk about, or you might not realize, is we're really assessing the quality of your actual skin, because a lot of plastic surgery is skin. It's more superficial level.",tier:'S',score:.903,hook:"What is a surgeon evaluating that you may not realize?",cover:'WHAT HE IS ACTUALLY EVALUATING',caption:"A consultation is not only about the procedure someone asks for. Dr. Frew is also looking at the tissue he would actually be working with — including skin quality — because that changes how he thinks through the plan.",cta:'Follow OPUS for more of the thinking behind the consultation.',reviewFlags:['editorial transcript trim — verify against source before export']},
 {id:'opus-f28e0d28b915',lane:'shorts',topic:'patient_experience',file:'MVI_8502.MOV',start:44.94,end:57.46,transcript:'What can make a before and after look impressive but tell you almost nothing? If the lighting is different in the before and after, or if the angle that the patient is at is different in the before and after.',tier:'S',score:.843,hook:'What can make a before-and-after look impressive — but tell you almost nothing?',cover:'THE PHOTO CAN CHANGE THE RESULT',caption:"Before-and-after photos are evidence only when the comparison is honest. Lighting and patient position can change what the eye thinks it sees. Those details matter.",cta:'Save this for the next time you evaluate results.',reviewFlags:['before/after language review']},
 {id:'opus-31e345937a0f',lane:'shorts',topic:'surgeon_judgment',file:'MVI_8496.MOV',start:140.74,end:171.88,transcript:'The patient should be in the same position in the before as in the after. We should have the same lighting because, depending on where the lighting is coming from, it can hide things. It can make things look different than what they actually are in real life.',tier:'S',score:.844,hook:'A before-and-after should be boringly consistent.',cover:'SAME POSITION. SAME LIGHT.',caption:"The less the photography changes, the more useful the comparison becomes. Same position. Same lighting. Less room for the image itself to manufacture the difference.",cta:'Save this as a before-and-after quality check.',reviewFlags:['before/after language review','editorial transcript trim — verify against source before export']},
 {id:'opus-dcb641f936fc',lane:'shorts',topic:'consultation',file:'IMG_6872.MOV',start:32.46,end:44.46,transcript:"We'll be handling all our consultations in here. So once a patient is done with their consultation, they'll come in here and I can guide them and speak to them about everything that the doctor went through with them.",tier:'S',score:.881,hook:'What happens after the surgeon leaves the consultation?',cover:'AFTER THE CONSULT, SOMEONE STAYS WITH YOU',caption:"The consultation does not end when the surgeon leaves the room. Tamara's role is to help carry the details forward — questions, next steps, and what was discussed — so the patient is not left to reconstruct everything alone.",cta:'Meet the people building the OPUS patient experience.',reviewFlags:['editorial transcript trim — verify against source before export']},
 {id:'opus-afb7e620170d',lane:'shorts',topic:'patient_experience',file:'MVI_8499.MOV',start:17.32,end:26.72,transcript:"Hello everyone, my name is Tamara. I'm one of the patient coordinators here at OPUS Plastic Surgery. I'm also the practice manager as well.",tier:'S',score:.890,hook:'Meet Tamara.',cover:'THE PERSON BETWEEN THE APPOINTMENTS',caption:"A well-run practice should feel almost invisible. Tamara is one of the people making that possible at OPUS — patient coordination, practice operations, and the details that connect one appointment to the next.",cta:'Meet Tamara, Patient Care Coordinator + Practice Manager.',reviewFlags:['proper name corrected from ASR; verify source title before export','slate word removed']},
 {id:'opus-ee247f427667',lane:'shorts',topic:'space_build',file:'MVI_8499.MOV',start:40.04,end:54.04,transcript:"What do you guys rate this room? I would rate it a zero — there's no coffee. I need my coffee in the morning. The next room right here will be our Botox, fillers, IV hydration.",tier:'S',score:.826,hook:'Tamara rates the unfinished OPUS rooms.',cover:'ZERO. NO COFFEE.',caption:"Tamara has notes. The practice is still under construction, which makes this exactly the right time to judge the rooms before they can defend themselves.",cta:'Follow the build before OPUS opens.',reviewFlags:['service-name review','editorial punctuation cleanup — verify against source before export']},
 {id:'opus-4976083473be',lane:'shorts',topic:'surgeon_judgment',file:'IMG_8006.MOV',start:98.75,end:113.53,transcript:'What looks reassuring when choosing a plastic surgeon but actually tells you very little? Follower count. You should go off of the reviews and you should go off of the actual before and afters that you see.',tier:'A',score:.808,hook:'Follower count is not evidence.',cover:'FOLLOWERS ARE NOT A CREDENTIAL',caption:"A large audience can feel reassuring. It is not the same thing as evidence. Dr. Frew points patients back toward the work itself and the experiences people report.",cta:'Save this for your surgeon research.',reviewFlags:['before/after language review']},
 {id:'opus-dfa0d1bd747f',lane:'google_business',topic:'consultation',file:'MVI_8496.MOV',start:500.18,end:523.66,transcript:"That is when I would say the patient comes in and has unrealistic expectations about what can be done for their body, or they want a surgery that is going to look unnatural for them. Or again, they're not a good candidate. They're not safe for surgery. We're not going to put anybody through that.",tier:'S',score:.859,hook:'Sometimes good judgment means saying no.',cover:'WHEN THE RIGHT PLAN IS NO SURGERY',caption:"A consultation is also an evaluation of whether surgery is appropriate at all. Expectations, candidacy and safety can change the answer — including when the answer should be no.",cta:'Learn more about how OPUS approaches consultation.',reviewFlags:['medical/safety language review','editorial transcript trim — verify against source before export']}
];
