export type CloudPackage = {
  id: string; lane: 'youtube_anchor'|'shorts'|'paid'|'stories'|'website'|'google_business'; topic: string;
  file: string; start: number; end: number; transcript: string; tier: 'S'|'A'|'B'; score: number;
  hook: string; cover: string; caption: string; cta: string; reviewFlags: string[];
};

export const cloudV2Summary = { runId:'opus-cloud-thursday-2026-09-10-v2', mediaFiles:23, candidates:148, sTier:28, aTier:100, totalPackages:29, needsReview:29, roughCuts:3 } as const;

export const cloudV2Packages: CloudPackage[] = [
 {id:'opus-04e9e898fc71',lane:'youtube_anchor',topic:'surgeon_judgment',file:'MVI_8496.MOV',start:76.91,end:99.83,transcript:"evaluating during a consultation that the patient may not realize you're evaluating? Okay, I think something that we don't always talk about or you might not realize is we're really assessing the quality of your actual skin because a lot of the surgery and plastic surgery is kind of skin. It's more superficial level",tier:'S',score:.903,hook:"evaluating during a consultation that the patient may not realize you're evaluating?",cover:'FROM OPUS',caption:"The point is not a perfect soundbite. It is seeing how the decisions get made.",cta:'Follow the build.',reviewFlags:[]},
 {id:'opus-afb7e620170d',lane:'shorts',topic:'patient_experience',file:'MVI_8499.MOV',start:17.32,end:26.72,transcript:"Action. Hello everyone, my name is Tamara. I'm one of the patient coordinators here at Ophis Plastic Surgery. I'm also the practice manager as well.",tier:'S',score:.890,hook:'Action.',cover:'THE DETAILS PATIENTS SHOULD NOT HAVE TO CARRY',caption:'OPUS is being built around details that shape the experience before, during, and around care.',cta:'Follow the build.',reviewFlags:['ASR proper-name check']},
 {id:'opus-dcb641f936fc',lane:'shorts',topic:'consultation',file:'IMG_6872.MOV',start:32.46,end:44.46,transcript:"We'll be handling all our consultations in here. So once a patient is done for consultation, they'll come in here and I can always guide them and speak to them about everything that the doctor went through with them.",tier:'S',score:.881,hook:"We'll be handling all our consultations in here.",cover:'WHAT MATTERS IN A CONSULT',caption:'A source-backed moment from the OPUS build and the people shaping it.',cta:'Follow the build.',reviewFlags:[]},
 {id:'opus-74ac91d15d69',lane:'paid',topic:'space_build',file:'MVI_8499.MOV',start:135.59,end:148.87,transcript:"Over here, this lovely office is the one and most amazing doctor. Dr. Frew's office. What's cool about this office too is it will connect to our consultation room where our lovely patients will be heading.",tier:'S',score:.876,hook:'Over here, this lovely office is the one and most amazing doctor.',cover:'WHAT HE SEES HERE',caption:'The space is still taking shape. The thinking behind it is already visible.',cta:'Join First Access.',reviewFlags:['paid always requires human/compliance review']},
 {id:'opus-cd0d0f822842',lane:'shorts',topic:'philosophy',file:'MVI_8496.MOV',start:0,end:13.34,transcript:"action. Hey everyone, it's Dr. Frew. Welcome to the Opus Update, but today I'm going to answer some of the questions that were submitted by you guys. Okay cut.",tier:'S',score:.861,hook:'action.',cover:'THE DECISION BEHIND THE DECISION',caption:'A source-backed moment from the OPUS build and the people shaping it.',cta:'Follow the build.',reviewFlags:[]},
 {id:'opus-dfa0d1bd747f',lane:'google_business',topic:'patient_experience',file:'MVI_8496.MOV',start:500.18,end:523.66,transcript:"wrong thing to do. That is when I would say the patient comes in and has unrealistic expectations about what can be done for their body or they want a surgery that is going to look unnatural for them. Or again, they're not a good candidate. They're not safe for surgery. We're not going to put anybody through that. At the end of the day, we want to",tier:'S',score:.859,hook:'wrong thing to do.',cover:'THE DETAILS PATIENTS SHOULD NOT HAVE TO CARRY',caption:'OPUS is being built around details that shape the experience before, during, and around care.',cta:'Follow OPUS for practice updates.',reviewFlags:['medical/safety language review']},
 {id:'opus-5f7aa4b997c9',lane:'shorts',topic:'surgeon_judgment',file:'MVI_8499.MOV',start:149.99,end:159.57,transcript:"I would rate these two rooms a two because the doctor is missing and there's no patient here.",tier:'S',score:.852,hook:"I would rate these two rooms a two because the doctor is missing and there's no patient here.",cover:'FROM OPUS',caption:'The point is not a perfect soundbite. It is seeing how the decisions get made.',cta:'Follow the build.',reviewFlags:[]},
 {id:'opus-b5d3e258961a',lane:'google_business',topic:'consultation',file:'IMG_8006.MOV',start:58.56,end:68.24,transcript:"What are you evaluating during a consultation that the patient may not realize you're evaluating?",tier:'S',score:.849,hook:"What are you evaluating during a consultation that the patient may not realize you're evaluating?",cover:'WHAT MATTERS IN A CONSULT',caption:'A source-backed moment from the OPUS build and the people shaping it.',cta:'Follow OPUS for practice updates.',reviewFlags:[]},
 {id:'opus-31e345937a0f',lane:'shorts',topic:'surgeon_judgment',file:'MVI_8496.MOV',start:140.74,end:171.88,transcript:"more standardized. The patient should be in the same position in the before as in the after. We should have the same lighting because depending on where the lighting is coming, it can hide things. It can make things look different than what they actually are in real life.",tier:'S',score:.844,hook:'more standardized.',cover:'FROM OPUS',caption:'The point is not a perfect soundbite. It is seeing how the decisions get made.',cta:'Follow the build.',reviewFlags:['before/after language review']},
 {id:'opus-f28e0d28b915',lane:'shorts',topic:'patient_experience',file:'MVI_8502.MOV',start:44.94,end:57.46,transcript:'What can make a before and after look impressive but tell you almost nothing? If the lighting is different in the before and after or if the angle that the patient is at is different in the before and after.',tier:'S',score:.843,hook:'What can make a before and after look impressive but tell you almost nothing?',cover:'THE DETAILS PATIENTS SHOULD NOT HAVE TO CARRY',caption:'OPUS is being built around details that shape the experience before, during, and around care.',cta:'Follow the build.',reviewFlags:['review source language: before and after']},
 {id:'opus-3af58930874a',lane:'shorts',topic:'default',file:'MVI_8496.MOV',start:118.55,end:140.74,transcript:'So I would say the quality of your skin. Next question. What can make a before and after look impressive but tell you almost nothing? The lighting in the angle. So it’s really important for you to look at the before and afters and they should be',tier:'S',score:.843,hook:'So I would say the quality of your skin.',cover:'FROM OPUS',caption:'A source-backed moment from the OPUS build and the people shaping it.',cta:'Follow the build.',reviewFlags:['review source language: before and after']},
 {id:'opus-ee247f427667',lane:'shorts',topic:'space_build',file:'MVI_8499.MOV',start:40.04,end:54.04,transcript:"What do you guys rate this room? I would rate it a zero, there's no coffee. I need my coffee in the morning. The next room right here will be our Botox Fillers Ivy Hydration.",tier:'S',score:.826,hook:'What do you guys rate this room?',cover:'WHAT HE SEES HERE',caption:'The space is still taking shape. The thinking behind it is already visible.',cta:'Follow the build.',reviewFlags:['service-name review']}
];
